### ISSUE TITLE
unwanted space was added while using -f parameter

### ISSUE THREAD

**Issue by amplatzer** [westhecool/python-apkpure#1]
~/Downloads/github/python-apkpure   main ±  python3 cli.py download com.google.android.youtube -f test.apk
 ~/Downloads/github/python-apkpure   main ±  ls test.apk
ls: test.apk: No such file or directory
 ~/Downloads/github/python-apkpure   main ±  ls test.apk\\
test.apk

there is extra space after the filename "test.apk"

**Comment by westhecool** [comment]
Fixed in: b3b892f2e989f11abde51e2a26600aabe7c7ce63
